# Generated by Django 4.1.7 on 2023-03-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_creates_at_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_publised',
            new_name='is_published',
        ),
    ]
